### ISSUE TITLE
Two way anova with bakR

### ISSUE THREAD

**Issue by AlessandroPilli** [simonlabcode/bakR#7]
Hi isac

I had previously contacted you for problems related to bam2bakR that you very kindly helped me solve and I thank you again. Now that everything is working perfectly I have a question related to the statistics part.

Since my experimental set includes data from a wild type sample, a sample with a knockout of a gene, a sample with a mutation of another gene and a sample that presents both knockout and mutation together, it would be perfect to use a TWO WAY ANOVA to evaluate the differences.

- For the differential stability part I used the hybrid model (HybridFit = TRUE) and I don't know if there is a way to include the two way.
- While for the differential synthesis analysis part, I believe that (but I'm not sure about it) Deseq2 can include in design the * to mimic the two way as follows:

dds <- DESeqDataSetFromMatrix(countData = Counts,
colData = colData,
design = ~conditions * interaction)

where interaction would be the different condition of the sample.

thanks,
Alessandro

**Comment by isaacvock** [comment]
Hello Alessandro,

Unfortunately, bakR is highly inflexible in the types of comparative analyses it can perform, and cannot accommodate the design matrix that you described. That is one of many things that inspired me to completely rewrite bakR and develop a new R package to replace bakR, called [EZbakR](https://github.com/isaacvock/EZbakR). One of the things that I am close to having fully implemented in EZbakR is flexible design-matrix specified comparative analyses. I will let you know when that is available and documented (probably by the end of next week). 

Once I have finished the EZbakR implementation, I might also be able to write you a script to take your current bakR output and perform a two-way anova with it, so that you can use the analyses you have already generated. I'll let you know if that turns out to be possible.

Best,
Isaac

**Comment by AlessandroPilli** [comment]
Thank you, then I'll wait for updates

**Comment by isaacvock** [comment]
Hello Alessandro,

I have finished implementing generalized linear modeling in EZbakR, and have documented this functionality [here](https://isaacvock.github.io/EZbakR/articles/Linear-modeling.html). Unfortunately, I was not able to come up with an easy way to take your current bakR output and perform EZbakR's modeling with it. Thankfully though, the input to EZbakR is very similar to bakR, but much more flexible (documented [here](https://isaacvock.github.io/EZbakR/articles/Quickstart.html)). Let me know if you have any questions, and if you run into any issues, please post them on the EZbakR [Issues page](https://github.com/isaacvock/EZbakR/issues).

For the sake of completeness, the workflow will look like:

```
library(dplyr)
library(data.table)
library(EZbakR)


# load cB
cB <- fread("path/to/cB.csv.gz")

# knockout and mutation could be TRUE/FALSE booleans
metadf <- tibble(sample = ..., tl = ...., knockout = ..., mutation = ....)

ezbdo <- EZbakRData(cB, metadf)

ezbdo <- EstimateFractions(ezbdo, features = "XF")

ezbdo <- EstimateKinetics(ezbdo)

# Fit model with interaction term
ezbdo <- AverageAndRegularize(ezbdo, parameter = "log_kdeg", formula_mean = ~ knockout*mutation)
ezbdo <- AverageAndRegularize(ezbdo, parameter = "log_ksyn", formula_mean = ~ knockout*mutation)

# Could also just fit interaction model (calculate averages in each combo of knockout and mutation
# which has some advantages to above model
ezbdo <- AverageAndRegularize(ezbdo, parameter = "log_kdeg", formula_mean = ~ knockout:mutation)
ezbdo <- AverageAndRegularize(ezbdo, parameter = "log_ksyn", formula_mean = ~ knockout:mutation)

# Assess parameters of interest with CompareParameters(); see documentation for details
```

I discuss this a bit in the documentation, but there are a couple ways to fit categorical interaction models

Best regards,
Isaac

**Comment by AlessandroPilli** [comment]
Hi Isac 

Just a couple more things:

1.  If I understood correctly EZbakR is providing results about the Differential synthesis analysis, but what about the Differential stability, is there a way to perform such analysis also for that part?


2. The function EZVolcanoPlot is used on an EZbakRCompare on which CompareParameters have been applied,  in my case:

ezbdo <- CompareParameters(ezbdo,
                           parameter = "log_kdeg",
                           design_factor = "",
                           reference = "knockoutWT:mutationWT",       # WT
                           experimental = "knockoutKO:mutationITD")  # AF (KO+ITD)

In the ezbdo object is called comparisonX (where X is the number related to the comparison that ran, in this case comparison1)

Now how do I specify that I want to plot only the part corresponding to this comparison (since there are no examples in the documentation if not for the first and very simple case)? Do I have to specify again the reference and experimental like the code that follows or there is a way to select the desired comparison via the specific name?

EZVolcanoPlot(ezbdo,
              parameter = "log_kdeg",
              reference = "knockoutWT:mutationWT",       # WT
              experimental = "knockoutKO:mutationITD")  # AF

**Comment by isaacvock** [comment]
Hi Alessandro,

1) No, the documentation shows EZbakR performing both differential stability and differential synthesis analyses. Running `AverageAndRegularize(ezbdo)` yields, by default, analyses of stability (`parameter="log_kdeg"`), and you can get synthesis rate analyses by setting the `parameter` argument to "log_ksyn". So both the stability and synthesis analyses should be in the `ezbdo$averages` list after these two calls to `AverageAndRegularize()`. Performing `CompareParameters(..., parameter = "log_kdeg")` will perform differential stability analyses and `CompareParameters(..., parameters = "log_ksyn")` will perform differential synthesis analyses. 
2) In general, whatever you specified in the arguments for `CompareParameters()` can be specified to `EZVolcanoPlot()` and `EZMAPlot()` in order to plot the result of a particular analysis. In particular, the `design_factor`, `reference`, `experimental`, and `param_name` arguments should correspond to whichever run of `CompareParameters()` you would like to visualize the results for. 

More specifically, you don't need to specify every single one of these arguments though, you just need to specify the minimal set that uniquely identifies a given comparative analysis. Say for example that you have run `CompareParameters()` twice, once with parameter = "log_ksyn" and once with parameter = "log_kdeg", and with the other parameters set to whatever you set them to. To visualize the differential stability result, you could just run `EZVolcanoPlot(ezbdo, parameter = "log_kdeg")` since you have only performed one differential stability analysis at this point, and thus this analysis is uniquely identifiable by you having set `parameter = "log_kdeg"` in `CompareParameters()`. So the code you showed should work in principle, but you may not need to specify all of `parameter`, `reference`, and `experimental` to get it to work in this case.

I'll work on adding documentation with examples of Volcano and MA plots for each of the comparison types I show in the linear modeling docs. Let me know if you have any other questions.

Best,
Isaac

**Comment by AlessandroPilli** [comment]
Hi Isaac, it is me once again,

I encountered a final problem during the use of EZbakR. 
I'm evaluating the synthesis results, but when executing CompareParameters with the parameter log_ksyn and not the evaluated interaction term but the single one, I'm getting a strange error that I'll report below. This is happening for both single-terms (knockoutKO and mutationITD")
I want to let you know that CompareParameters with the single therms worked when using log_kdeg and worked with log_ksyn only in the case of the interaction term:


Here the command executed and the error.
> ezbdo <- AverageAndRegularize(ezbdo, parameter = "log_ksyn", formula_mean = ~ knockout*mutation)

> ezbdo$metadata$averages$logksyn_XF$fit_params
[1] "knockoutWT"             "knockoutKO"             "mutationITD"           
[4] "knockoutKO:mutationITD"

> ezbdo <- CompareParameters(ezbdo, 
                            parameter = "log_ksyn",       
                            param_name = "knockoutKO") 
**Error in obj[["comparisons"]][[output_name]] <- dplyr::as_tibble(comparison) : 
  attempt to select less than one element in OneIndex**
  

Best,
Alessandro

**Comment by isaacvock** [comment]
Hi Alessandro,

I was able to reproduce the bug on my end and just pushed a fix. Update EZbakR with `devtools::install_github("isaacvock/EZbakR")`. You should then be able to run CompareParameters() without modifying any of your current parameters. Let me know if you continue to run into issues even after the update.

Details if you are interested: problem was just in how EZbakR tries to decide the name of the output table. So CompareParameters() probably ran fine for you, up until the very last step of saving the output to the EZbakRData object, where the proposed name for the output was an empty vector (leading to the `attempt to select less than one element in OneIndex` error).

Best,
Isaac

**Comment by AlessandroPilli** [comment]
Updating the package worked, but now the last problem is the evaluation of the single terms regarding the KO.
These are the parameters that I can set in CompareParameters together with log_kdeg
> ezbdo$metadata$averages$logkdeg_XF$fit_params
[1] "knockoutWT"             "knockoutKO"             "mutationITD"            "knockoutKO:mutationITD"

When using the interaction therm evaluated "knockoutKO:mutationITD"
 and "mutationITD" I obtained good results. i rebuilt the plots using the p_val instead of the adjusted

This is the one obtained by using the interaction term:
![image](https://github.com/user-attachments/assets/4b7cbf54-dc35-49db-8a52-f9544e26f28e)

And this is the one using mutationITD:
![image](https://github.com/user-attachments/assets/34639d4a-e716-4ec5-9a41-83a5a66fe489)

But when doing the same for knockoutKO the result is completely unexpected. When performing the analysis with just bakR that used the same cB file this kind of result was not showing.
![image](https://github.com/user-attachments/assets/a1fca3bb-e8a4-43ac-b9da-1c8d9d02bbfc)

And this plot is very similar to the one generated by 
EZVolcanoPlot(ezbdo,
                      parameter = "log_kdeg",
                      param_name = "knockoutKO")
![image](https://github.com/user-attachments/assets/5ac827a4-a08a-4388-a8dd-25b75a1a43dc)

Let me know what you think, or if I'm doing something wrong.

Best regards
Alessandro

**Comment by isaacvock** [comment]
Hi Alessandro,

I'm out of the office today so this will be a quick response that I may need to follow up on tonight, but I think you are just misinterpreting the parameters in your model, due to the quirks of categorical interaction models. knockoutKO in this case should just be the average log(kdeg) of a given transcript in KO cells. The p value in this case is meaningless, and it should not be used to make volcano plots. Unintuitively, the mutaionITD parameter represents the effect of the mutation on just the WT genotype. Thus, unlike the parameter knockoutKO, it makes sense to run CompareParameter() on just that parameter, as it represents a difference between conditions. To compare the KO and WT stabilities, run CompareParameters() as described in the documentation for the interaction model: https://isaacvock.github.io/EZbakR/articles/Linear-modeling.html

Best,
Isaac

**Comment by AlessandroPilli** [comment]
Dear Isaac, 

Since I'm integrating my results with an RNA-seq analysis I wanted to perform the same steps with the TimeLapse data using old and new reads together treating them as a normal RNA sequencing. 
To do so, is it correct to use the various files *.featureCounts* stored in the *../bam2bakR/results/featurecounts_genes* that are coming from the bam2bakR pipeline or should I use something else?

Best
Alessandro

**Comment by isaacvock** [comment]
You could use those files, or alternatively you can generate a regular read count matrix from the cB file as such:

```
library(dplyr)
library(tidyr)

# One column per sample, entries will be read counts
# Will also include a feature column (XF in this case)
count_df <- cB %>% 
  filter(XF != "__no_feature" & !is.na(XF)) %>% 
  group_by(sample, XF) %>% 
  summarise(reads = sum(n)) %>% 
  pivot_wider(names_from = sample, values_from = reads)

# Convert to matrix and replace NAs with 0s
count_matrix <- count_df[,-1] %>% as.matrix()
rownames(count_matrix) <- count_df$XF
count_matrix[is.na(count_matrix)] <- 0
```

This count matrix could then be provided to tools like DESeq2.

Best,
Isaac

**Comment by AlessandroPilli** [comment]
Hi Isaac thanks for the code, works perfectly but to double check I compared the results with those in the *featureCounts* file, and the values are different, do you have an explenation for it?

AF_1 column from **count_matrix**:
![image](https://github.com/user-attachments/assets/6d0bfbd7-9706-4606-8dfe-73eb2c31dbad)

**featureCount** file for AF_1:
![image](https://github.com/user-attachments/assets/80265f2e-f075-4b05-b9a6-32afa2a46f31)

**Comment by isaacvock** [comment]
Hi Alessandro,

You are probably looking at the read counts in the "featurecounts_genes" folder, which includes exonic and intronic mapping read counts. Compare it to the output in the "festurecounts_exons" folder for a fair comparison. 

If you want to include intronic reads in your read counts, just change every instance of `XF` in the code in my last message to `GF`.

Best, 
Isaac
